#!/usr/bin/env python3
"""Regressions: optional window settings, sidebar/traffic light safety and Messages startup."""
from __future__ import annotations
import os
from pathlib import Path
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]


class WindowSettingsAndMessageLaunch(unittest.TestCase):
    def test_hyprland_does_not_source_optional_windows_file(self):
        src = (ROOT / "compositor/hyprland/hyprland.conf").read_text()
        for line in src.splitlines():
            if line.lstrip().startswith("source ="):
                self.assertNotIn("windows.conf", line)
        self.assertIn("source = ~/.config/hypr/golden-gate/machine.conf", src)

    def test_machine_config_accepts_missing_and_existing_windows_file(self):
        generator = ROOT / "compositor/hyprland/machine-conf.sh"
        with tempfile.TemporaryDirectory() as temp:
            base = Path(temp)
            out = base / "golden-gate/machine.conf"
            env = {**os.environ, "LIBGL_ALWAYS_SOFTWARE": "1"}
            for exists in (False, True):
                windows = out.with_name("windows.conf")
                if exists:
                    windows.write_text("general {\n    snap {\n        window_gap = 23\n    }\n}\n")
                subprocess.run(["sh", str(generator), str(out)], env=env, check=True,
                               capture_output=True, text=True)
                conf = out.read_text()
                self.assertNotIn("source =", conf)
                self.assertIn("Generated by machine-conf.sh", conf)
                self.assertEqual("window_gap = 23" in conf, exists)

    def test_sidebar_buttons_never_enter_traffic_light_zone(self):
        shared = (ROOT / "apps/lib/AppWindow.qml").read_text()
        self.assertIn("readonly property real toolbarSafeX: lights.x + lights.width + 16", shared)
        # These applications can animate their sidebar down to zero width.
        for app in ("settings", "files", "mail", "calendar"):
            source = (ROOT / f"apps/{app}.qml").read_text()
            self.assertIn("Math.max(win.contentX +", source, app)
            self.assertIn("win.toolbarSafeX)", source, app)
        # The dedicated sidebar-side toolbar already has a safe lower bound.
        self.assertIn("Math.max(lights.x + lights.width + 16,", shared)

    def test_messages_starts_with_error_reporting_and_real_onboarding(self):
        desktop = (ROOT / "apps/desktop/org.goldengate.Messages.desktop").read_text()
        opener = (ROOT / "apps/messages/open.sh").read_text()
        qml = (ROOT / "apps/messages.qml").read_text()
        onboarding = (ROOT / "apps/messages/Onboarding.qml").read_text()
        checks = (ROOT / "tests/qml-load.py").read_text()
        self.assertIn("Exec=sh @APPS@/messages/open.sh", desktop)
        self.assertIn('qs -n -p "$apps/messages.qml"', opener)
        self.assertIn("golden-gate-messages.log", opener)
        self.assertIn("ContactCard {", qml)
        self.assertIn('objectName: "messagesOnboarding"', onboarding)
        self.assertIn('("messages-onboarding", ["app", "apps/messages.qml"', checks)


if __name__ == "__main__":
    unittest.main(verbosity=2)
