// Generated by design/build.mjs from tokens.json. Do not edit.
pragma Singleton
import QtQuick

QtObject {
    property bool dark: false

    readonly property string fontUi: "SF Pro Text"
    readonly property string fontDisplay: "SF Pro Display"
    readonly property real textCaption2: 10
    readonly property real textCaption: 11
    readonly property real textFootnote: 12
    readonly property real textBody: 13
    readonly property real textCallout: 14
    readonly property real textHeadline: 13
    readonly property real textTitle3: 15
    readonly property real textTitle2: 17
    readonly property real textTitle1: 22
    readonly property real textLargeTitle: 26
    readonly property real radiusControl: 6
    readonly property real radiusMenuItem: 8
    readonly property real radiusMenu: 14
    readonly property real radiusField: 18
    readonly property real radiusCapsule: 999
    readonly property real radiusTile: 26
    readonly property real radiusWindow: 22
    readonly property real radiusSidebar: 16
    readonly property real radiusDock: 26
    readonly property real sizeMenubar: 30
    readonly property real sizeToolbar: 52
    readonly property real sizeToolbarPill: 36
    readonly property real sizeTrafficLight: 13
    readonly property real sizeSidebar: 220
    readonly property real sizeDockIcon: 54
    readonly property real sizeDockMagnified: 86
    readonly property real sizeCcModule: 64
    readonly property real sizeCcWidth: 300
    readonly property color accentBlue: "#0a84ff"
    readonly property color accentPurple: "#bf5af2"
    readonly property color accentPink: "#ff375f"
    readonly property color accentRed: "#ff453a"
    readonly property color accentOrange: "#ff9f0a"
    readonly property color accentYellow: "#ffd60a"
    readonly property color accentGreen: "#30d158"
    readonly property color accentGraphite: "#8e8e93"
    property string accentName: "blue"
    property string glassStyle: "clear"
    property bool reduceTransparency: false
    property bool reduceMotion: false
    property bool alwaysShowScrollbars: false
    property real glassSolidity: 0
    property real textScale: 1
    function fs(n) { return n > 24 ? n : Math.round(n * Math.max(1, Math.min(1.5, textScale))) }
    // Control heights follow the text: fh(26) for a 26 px control.
    function fh(n) { return Math.round(n * (1 + (Math.max(1, Math.min(1.5, textScale)) - 1) * 0.8)) }
    readonly property color accent: ({ blue: accentBlue, teal: accentBlue, purple: accentPurple, pink: accentPink, red: accentRed, orange: accentOrange, yellow: accentYellow, green: accentGreen, slate: accentGraphite })[accentName] ?? accentBlue
    readonly property color windowBg: dark ? "#1e1e1e" : "#ffffff"
    readonly property color contentBg: dark ? "#1a1a1a" : "#ffffff"
    readonly property color sidebarBg: dark ? "#d92a282e" : "#d1f6f6f8"
    readonly property color label: dark ? "#ebffffff" : "#e0000000"
    readonly property color secondaryLabel: dark ? "#8cffffff" : "#8c000000"
    readonly property color tertiaryLabel: dark ? "#40ffffff" : "#47000000"
    readonly property color separator: dark ? "#1affffff" : "#17000000"
    readonly property color fill: dark ? "#12ffffff" : "#0d000000"
    readonly property color selection: dark ? "#1affffff" : "#12000000"
    readonly property color menuHighlight: dark ? "#1affffff" : "#0f000000"
    readonly property QtObject glassClear: QtObject {
        readonly property real blur: 24
        readonly property color tint: dark ? "#571c1c20" : "#5cffffff"
        readonly property color rim: dark ? "#5cffffff" : "#b3ffffff"
        readonly property color rimLow: dark ? "#1fffffff" : "#4dffffff"
        readonly property color shine: dark ? "#14ffffff" : "#42ffffff"
        readonly property color edge: "#1a000000"
        readonly property real lens: 10
        readonly property real shadowY: 5
        readonly property real shadowOpacity: 0.18
        readonly property real tinted: 0.72
        readonly property real reduced: 0.94
    }
    readonly property QtObject glassRegular: QtObject {
        readonly property real blur: 32
        readonly property color tint: dark ? "#ad202024" : "#b8fafafc"
        readonly property color rim: dark ? "#4dffffff" : "#a8ffffff"
        readonly property color rimLow: dark ? "#1affffff" : "#3dffffff"
        readonly property color shine: dark ? "#0fffffff" : "#38ffffff"
        readonly property color edge: "#1f000000"
        readonly property real lens: 12
        readonly property real shadowY: 6
        readonly property real shadowOpacity: 0.22
        readonly property real tinted: 0.88
        readonly property real reduced: 0.96
    }
    readonly property QtObject menu: QtObject {
        readonly property real blur: 40
        readonly property color tint: dark ? "#c726262a" : "#ccf6f6f8"
        readonly property color rim: dark ? "#38ffffff" : "#94ffffff"
        readonly property color rimLow: dark ? "#14ffffff" : "#33ffffff"
        readonly property color shine: dark ? "#0affffff" : "#29ffffff"
        readonly property color edge: "#1a000000"
        readonly property real lens: 8
        readonly property real shadowY: 10
        readonly property real shadowOpacity: 0.28
        readonly property real tinted: 0.92
        readonly property real reduced: 0.97
    }
    readonly property QtObject glassControl: QtObject {
        readonly property real blur: 20
        readonly property color tint: dark ? "#9948484e" : "#dbffffff"
        readonly property color rim: dark ? "#42ffffff" : "#b8ffffff"
        readonly property color rimLow: dark ? "#1affffff" : "#42ffffff"
        readonly property color shine: dark ? "#0dffffff" : "#33ffffff"
        readonly property color edge: "#14000000"
        readonly property real lens: 5
        readonly property real shadowY: 2
        readonly property real shadowOpacity: 0.14
        readonly property real tinted: 0.94
        readonly property real reduced: 0.98
    }
    readonly property QtObject glassSidebar: QtObject {
        readonly property real blur: 40
        readonly property color tint: dark ? "#9428282c" : "#9ef4f4f7"
        readonly property color rim: dark ? "#24ffffff" : "#6bffffff"
        readonly property color rimLow: dark ? "#0dffffff" : "#1fffffff"
        readonly property color shine: dark ? "#08ffffff" : "#1fffffff"
        readonly property color edge: "#0f000000"
        readonly property real lens: 0
        readonly property real shadowY: 2
        readonly property real shadowOpacity: 0.1
        readonly property real tinted: 0.86
        readonly property real reduced: 0.97
    }
    readonly property QtObject glassDock: QtObject {
        readonly property real blur: 24
        readonly property color tint: dark ? "#7021262e" : "#5f343941"
        readonly property color rim: dark ? "#42ffffff" : "#57ffffff"
        readonly property color rimLow: dark ? "#1affffff" : "#29ffffff"
        readonly property color shine: dark ? "#0fffffff" : "#1affffff"
        readonly property color edge: "#1f000000"
        readonly property real lens: 4
        readonly property real shadowY: 5
        readonly property real shadowOpacity: 0.3
        readonly property real tinted: 0.8
        readonly property real reduced: 0.94
    }

    // Springs: use as NumberAnimation { duration: Theme.snappy.duration; easing.type: Easing.BezierSpline; easing.bezierCurve: Theme.snappy.curve }
    readonly property QtObject smooth: QtObject {
        readonly property int duration: 631
        readonly property var curve: [0.012, 0.0001, 0.0239, 0.0178, 0.0359, 0.0441, 0.0602, 0.0973, 0.0845, 0.183, 0.1088, 0.2655, 0.1419, 0.3778, 0.1751, 0.4858, 0.2082, 0.5718, 0.2487, 0.6771, 0.2893, 0.7526, 0.3299, 0.807, 0.3771, 0.8702, 0.4242, 0.9063, 0.4714, 0.9308, 0.5246, 0.9584, 0.5779, 0.9713, 0.6311, 0.9797, 0.6899, 0.9891, 0.7488, 0.9927, 0.8076, 0.9951, 0.8718, 0.9976, 0.9359, 1, 1, 1]
    }
    readonly property QtObject snappy: QtObject {
        readonly property int duration: 488
        readonly property var curve: [0.012, 0, 0.0239, 0.0162, 0.0359, 0.0413, 0.0602, 0.0922, 0.0845, 0.1776, 0.1088, 0.2635, 0.1419, 0.3806, 0.1751, 0.4989, 0.2082, 0.5939, 0.2487, 0.7103, 0.2893, 0.7945, 0.3299, 0.8523, 0.3771, 0.9194, 0.4242, 0.9532, 0.4714, 0.9731, 0.5246, 0.9956, 0.5779, 1.0011, 0.6311, 1.0036, 0.6899, 1.0063, 0.7488, 1.0048, 0.8076, 1.0038, 0.8718, 1.0026, 0.9359, 1, 1, 1]
    }
    readonly property QtObject bouncy: QtObject {
        readonly property int duration: 704
        readonly property var curve: [0.012, 0.0001, 0.0239, 0.0225, 0.0359, 0.0572, 0.0602, 0.1277, 0.0845, 0.2459, 0.1088, 0.3606, 0.1419, 0.5168, 0.1751, 0.6656, 0.2082, 0.772, 0.2487, 0.9024, 0.2893, 0.9743, 0.3299, 1.01, 0.3771, 1.0516, 0.4242, 1.0494, 0.4714, 1.0422, 0.5246, 1.0341, 0.5779, 1.0193, 0.6311, 1.0112, 0.6899, 1.0022, 0.7488, 0.9991, 0.8076, 0.9982, 0.8718, 0.9973, 0.9359, 1, 1, 1]
    }
    readonly property QtObject popover: QtObject {
        readonly property int duration: 435
        readonly property var curve: [0.012, 0, 0.0239, 0.0146, 0.0359, 0.0378, 0.0602, 0.085, 0.0845, 0.1665, 0.1088, 0.2517, 0.1419, 0.3677, 0.1751, 0.49, 0.2082, 0.5907, 0.2487, 0.714, 0.2893, 0.8068, 0.3299, 0.8699, 0.3771, 0.9433, 0.4242, 0.9792, 0.4714, 0.9983, 0.5246, 1.0199, 0.5779, 1.0211, 0.6311, 1.0195, 0.6899, 1.0178, 0.7488, 1.0122, 0.8076, 1.0086, 0.8718, 1.0046, 0.9359, 1, 1, 1]
    }
    readonly property QtObject dock: QtObject {
        readonly property int duration: 253
        readonly property var curve: [0.012, 0, 0.0239, 0.0148, 0.0359, 0.0377, 0.0602, 0.0842, 0.0845, 0.1624, 0.1088, 0.2418, 0.1419, 0.3501, 0.1751, 0.4611, 0.2082, 0.5523, 0.2487, 0.6641, 0.2893, 0.7487, 0.3299, 0.8093, 0.3771, 0.8798, 0.4242, 0.9198, 0.4714, 0.9456, 0.5246, 0.9746, 0.5779, 0.9859, 0.6311, 0.9925, 0.6899, 0.9997, 0.7488, 1.0008, 0.8076, 1.0013, 0.8718, 1.0019, 0.9359, 1, 1, 1]
    }
    readonly property QtObject window: QtObject {
        readonly property int duration: 539
        readonly property var curve: [0.012, 0, 0.0239, 0.0159, 0.0359, 0.0405, 0.0602, 0.0903, 0.0845, 0.1738, 0.1088, 0.2577, 0.1419, 0.3721, 0.1751, 0.4877, 0.2082, 0.5811, 0.2487, 0.6955, 0.2893, 0.7792, 0.3299, 0.8376, 0.3771, 0.9054, 0.4242, 0.941, 0.4714, 0.9629, 0.5246, 0.9876, 0.5779, 0.9952, 0.6311, 0.9993, 0.6899, 1.0037, 0.7488, 1.0032, 0.8076, 1.0028, 0.8718, 1.0023, 0.9359, 1, 1, 1]
    }
}
