// Generated by design/build.mjs from tokens.json. Do not edit.
pragma Singleton
import QtQuick

QtObject {
    property bool dark: false

    readonly property string fontUi: "SF Pro Text"
    readonly property string fontDisplay: "SF Pro Display"
    readonly property real textCaption2: 10
    readonly property real textCaption: 11
    readonly property real textFootnote: 12
    readonly property real textBody: 13
    readonly property real textCallout: 14
    readonly property real textHeadline: 13
    readonly property real textTitle3: 15
    readonly property real textTitle2: 17
    readonly property real textTitle1: 22
    readonly property real textLargeTitle: 26
    readonly property real radiusControl: 6
    readonly property real radiusMenuItem: 8
    readonly property real radiusMenu: 14
    readonly property real radiusField: 18
    readonly property real radiusCapsule: 999
    readonly property real radiusTile: 26
    readonly property real radiusWindow: 22
    readonly property real radiusSidebar: 16
    readonly property real radiusDock: 26
    readonly property real sizeMenubar: 30
    readonly property real sizeToolbar: 52
    readonly property real sizeToolbarPill: 36
    readonly property real sizeTrafficLight: 13
    readonly property real sizeSidebar: 220
    readonly property real sizeDockIcon: 54
    readonly property real sizeDockMagnified: 86
    readonly property real sizeCcModule: 64
    readonly property real sizeCcWidth: 300
    readonly property color accentBlue: "#0a84ff"
    readonly property color accentPurple: "#bf5af2"
    readonly property color accentPink: "#ff375f"
    readonly property color accentRed: "#ff453a"
    readonly property color accentOrange: "#ff9f0a"
    readonly property color accentYellow: "#ffd60a"
    readonly property color accentGreen: "#30d158"
    readonly property color accentGraphite: "#8e8e93"
    property string accentName: "blue"
    property string glassStyle: "clear"
    property bool reduceTransparency: false
    property bool reduceMotion: false
    readonly property color accent: ({ blue: accentBlue, teal: accentBlue, purple: accentPurple, pink: accentPink, red: accentRed, orange: accentOrange, yellow: accentYellow, green: accentGreen, slate: accentGraphite })[accentName] ?? accentBlue
    readonly property color windowBg: dark ? "#1e1e1e" : "#ffffff"
    readonly property color contentBg: dark ? "#1a1a1a" : "#ffffff"
    readonly property color sidebarBg: dark ? "#9e2e2c34" : "#b8f6f6f8"
    readonly property color label: dark ? "#ebffffff" : "#e0000000"
    readonly property color secondaryLabel: dark ? "#8cffffff" : "#8c000000"
    readonly property color tertiaryLabel: dark ? "#40ffffff" : "#47000000"
    readonly property color separator: dark ? "#1affffff" : "#17000000"
    readonly property color fill: dark ? "#12ffffff" : "#0d000000"
    readonly property color selection: dark ? "#1affffff" : "#12000000"
    readonly property color menuHighlight: dark ? "#1affffff" : "#0f000000"
    readonly property QtObject glassClear: QtObject {
        readonly property real blur: 24
        readonly property color tint: dark ? "#61283c6e" : "#6bffffff"
        readonly property color rim: "#b8ffffff"
        readonly property color rimLow: "#33ffffff"
        readonly property color shine: "#85ffffff"
    }
    readonly property QtObject glassRegular: QtObject {
        readonly property real blur: 32
        readonly property color tint: dark ? "#ad242428" : "#b8fafafc"
        readonly property color rim: "#b3ffffff"
        readonly property color rimLow: "#1affffff"
        readonly property color shine: "#73ffffff"
    }
    readonly property QtObject menu: QtObject {
        readonly property real blur: 40
        readonly property color tint: dark ? "#b328282c" : "#bdf6f6f8"
        readonly property color rim: "#bfffffff"
        readonly property color rimLow: "#1fffffff"
        readonly property color shine: "#66ffffff"
    }

    // Springs: use as NumberAnimation { duration: Theme.snappy.duration; easing.type: Easing.BezierSpline; easing.bezierCurve: Theme.snappy.curve }
    readonly property QtObject smooth: QtObject {
        readonly property int duration: 734
        readonly property var curve: [0.012, 0.0001, 0.0239, 0.0179, 0.0359, 0.0441, 0.0602, 0.0974, 0.0845, 0.1831, 0.1088, 0.2656, 0.1419, 0.378, 0.1751, 0.486, 0.2082, 0.572, 0.2487, 0.6773, 0.2893, 0.7528, 0.3299, 0.8071, 0.3771, 0.8703, 0.4242, 0.9064, 0.4714, 0.9308, 0.5246, 0.9585, 0.5779, 0.9713, 0.6311, 0.9798, 0.6899, 0.9891, 0.7488, 0.9927, 0.8076, 0.9951, 0.8718, 0.9976, 0.9359, 1, 1, 1]
    }
    readonly property QtObject snappy: QtObject {
        readonly property int duration: 557
        readonly property var curve: [0.012, 0, 0.0239, 0.0162, 0.0359, 0.0412, 0.0602, 0.092, 0.0845, 0.1772, 0.1088, 0.263, 0.1419, 0.38, 0.1751, 0.4981, 0.2082, 0.5932, 0.2487, 0.7095, 0.2893, 0.7938, 0.3299, 0.8517, 0.3771, 0.9189, 0.4242, 0.9528, 0.4714, 0.9729, 0.5246, 0.9955, 0.5779, 1.001, 0.6311, 1.0036, 0.6899, 1.0063, 0.7488, 1.0048, 0.8076, 1.0038, 0.8718, 1.0027, 0.9359, 1, 1, 1]
    }
    readonly property QtObject bouncy: QtObject {
        readonly property int duration: 818
        readonly property var curve: [0.012, 0.0001, 0.0239, 0.0224, 0.0359, 0.0571, 0.0602, 0.1275, 0.0845, 0.2456, 0.1088, 0.3602, 0.1419, 0.5163, 0.1751, 0.665, 0.2082, 0.7715, 0.2487, 0.902, 0.2893, 0.974, 0.3299, 1.0098, 0.3771, 1.0515, 0.4242, 1.0494, 0.4714, 1.0423, 0.5246, 1.0342, 0.5779, 1.0194, 0.6311, 1.0113, 0.6899, 1.0023, 0.7488, 0.9991, 0.8076, 0.9982, 0.8718, 0.9973, 0.9359, 1, 1, 1]
    }
    readonly property QtObject popover: QtObject {
        readonly property int duration: 501
        readonly property var curve: [0.012, 0, 0.0239, 0.0146, 0.0359, 0.0378, 0.0602, 0.085, 0.0845, 0.1666, 0.1088, 0.2518, 0.1419, 0.3678, 0.1751, 0.4901, 0.2082, 0.5908, 0.2487, 0.7141, 0.2893, 0.8069, 0.3299, 0.87, 0.3771, 0.9434, 0.4242, 0.9793, 0.4714, 0.9984, 0.5246, 1.0199, 0.5779, 1.0211, 0.6311, 1.0195, 0.6899, 1.0178, 0.7488, 1.0122, 0.8076, 1.0086, 0.8718, 1.0046, 0.9359, 1, 1, 1]
    }
    readonly property QtObject dock: QtObject {
        readonly property int duration: 293
        readonly property var curve: [0.012, 0, 0.0239, 0.0148, 0.0359, 0.0377, 0.0602, 0.0842, 0.0845, 0.1624, 0.1088, 0.2419, 0.1419, 0.3502, 0.1751, 0.4612, 0.2082, 0.5524, 0.2487, 0.6642, 0.2893, 0.7488, 0.3299, 0.8094, 0.3771, 0.8799, 0.4242, 0.9199, 0.4714, 0.9456, 0.5246, 0.9746, 0.5779, 0.9859, 0.6311, 0.9925, 0.6899, 0.9998, 0.7488, 1.0008, 0.8076, 1.0013, 0.8718, 1.0019, 0.9359, 1, 1, 1]
    }
    readonly property QtObject window: QtObject {
        readonly property int duration: 622
        readonly property var curve: [0.012, 0, 0.0239, 0.016, 0.0359, 0.0405, 0.0602, 0.0903, 0.0845, 0.1738, 0.1088, 0.2578, 0.1419, 0.3722, 0.1751, 0.4878, 0.2082, 0.5812, 0.2487, 0.6956, 0.2893, 0.7793, 0.3299, 0.8376, 0.3771, 0.9054, 0.4242, 0.9411, 0.4714, 0.963, 0.5246, 0.9876, 0.5779, 0.9953, 0.6311, 0.9993, 0.6899, 1.0037, 0.7488, 1.0032, 0.8076, 1.0028, 0.8718, 1.0023, 0.9359, 1, 1, 1]
    }
}
