// A glyph from lib/assets/symbols (generated by icons/build.mjs, like the shell's).
//   tone: "auto" (dark on light, white on dark) | "white" | "accent" | "dark" | "gray" | "red"
// The accent files are blue; with another system accent colour they're tinted on
// the GPU (MultiEffect), and stay blue under the software renderer.
import QtQuick
import QtQuick.Effects
import "theme"

Item {
    id: root
    property string name
    property string tone: "auto"
    property color color: "transparent"
    property real size: 17
    readonly property string resolved: tone === "auto" ? (Theme.dark ? "white" : "dark") : tone
    readonly property color tint: color.a > 0
        ? color
        : resolved === "accent" && Theme.accentName !== "blue"
            ? Theme.accent
            : "transparent"
    readonly property bool tinted: tint.a > 0 && GraphicsInfo.api !== GraphicsInfo.Software
    width: size; height: size
    implicitWidth: size; implicitHeight: size

    Image {
        id: img
        anchors.fill: parent
        source: root.name ? Qt.resolvedUrl("assets/symbols/" + root.name + (root.resolved === "white" ? "" : "@" + root.resolved) + ".svg") : ""
        sourceSize: Qt.size(root.size * 2, root.size * 2)
        smooth: true
        visible: !root.tinted
    }
    MultiEffect {
        anchors.fill: img
        source: img
        visible: root.tinted
        colorization: 1.0
        colorizationColor: root.tint
    }
}
