#!/usr/bin/env node
// Compiles design/tokens.json into per-platform theme files:
//   dist/tokens.css            CSS custom properties + spring easings (prototype, web apps)
//   dist/Theme.qml + qmldir    QML singleton (Quickshell shell)
//   dist/gtk.css               libadwaita / GTK4 colour + shape overrides
//   dist/hyprland-motion.conf  compositor beziers + animation timings
//
// Usage: node design/build.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const t = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));
const out = join(here, "dist");
mkdirSync(out, { recursive: true });

const kebab = (s) => s.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());
const round = (n, p = 4) => Number(n.toFixed(p));

// ---------------------------------------------------------------- springs
// Unit-mass damped harmonic oscillator released from 0 towards 1, using the
// SwiftUI parameterisation (response = undamped period, dampingFraction = zeta).
export function spring({ response, dampingFraction: z }) {
  const w0 = (2 * Math.PI) / response;
  const pos = (t) => {
    if (z < 1) {
      const wd = w0 * Math.sqrt(1 - z * z);
      return 1 - Math.exp(-z * w0 * t) * (Math.cos(wd * t) + ((z * w0) / wd) * Math.sin(wd * t));
    }
    return 1 - Math.exp(-w0 * t) * (1 + w0 * t);
  };
  // Settling time: last moment the curve is further than 0.1% from rest.
  let settle = 0;
  for (let t = 0; t < 5; t += 0.001) if (Math.abs(1 - pos(t)) > 0.001) settle = t;
  settle = Math.max(settle, 0.05);
  return { pos, duration: Math.round(settle * 1000), stiffness: w0 * w0, damping: 2 * z * w0, overshoots: z < 1 };
}

function cssLinear(s, samples = 40) {
  const pts = [];
  for (let i = 0; i <= samples; i++) {
    const x = i / samples;
    pts.push(round(s.pos(x * (s.duration / 1000)), 4));
  }
  pts[pts.length - 1] = 1;
  return `linear(${pts.join(", ")})`;
}

// Qt's Easing.BezierSpline takes consecutive cubic segments [c1x,c1y,c2x,c2y,x,y,...]
// starting at (0,0) and ending at (1,1). We fit a Hermite spline through samples.
// Qt's BezierEase keeps its segments in a fixed 8-entry buffer: longer splines
// write out of bounds and corrupt the heap (found with valgrind). Stay at 8.
function qtBezierSpline(s, segments = 8) {
  const T = s.duration / 1000;
  const f = (x) => (x >= 1 ? 1 : s.pos(x * T));
  const d = (x) => (f(Math.min(1, x + 1e-4)) - f(Math.max(0, x - 1e-4))) / (Math.min(1, x + 1e-4) - Math.max(0, x - 1e-4));
  const curve = [];
  for (let i = 0; i < segments; i++) {
    // Denser sampling at the start where curvature is highest.
    const a = Math.pow(i / segments, 1.6), b = Math.pow((i + 1) / segments, 1.6);
    const h = b - a;
    const ya = f(a), yb = i === segments - 1 ? 1 : f(b);
    curve.push(a + h / 3, ya + (d(a) * h) / 3, b - h / 3, yb - (i === segments - 1 ? 0 : (d(b) * h) / 3), b, yb);
  }
  return curve.map((n) => round(n, 4));
}

// Hyprland only has single cubic beziers, so approximate: overshoot is folded into y1.
function hyprBezier(z) {
  if (z >= 1) return [0.22, 1, 0.36, 1];
  return [0.3, round(1 + (1 - z) * 1.6, 2), 0.4, 1];
}

const springs = Object.fromEntries(Object.entries(t.motion.spring).map(([k, v]) => [k, { ...v, ...spring(v) }]));

// ---------------------------------------------------------------- CSS
function material(name, m) {
  const p = `--mat-${kebab(name)}`;
  return [
    `${p}-filter: blur(${m.blur}px) saturate(${m.saturate}) brightness(${m.brightness});`,
    `${p}-tint: ${m.tintLight};`,
    `${p}-tint-dark: ${m.tintDark};`,
    `${p}-rim: ${m.rim};`,
    `${p}-rim-low: ${m.rimLow};`,
    `${p}-shine: ${m.shine};`,
    `${p}-rim-dark: ${m.rimDark ?? m.rim};`,
    `${p}-rim-low-dark: ${m.rimLowDark ?? m.rimLow};`,
    `${p}-shine-dark: ${m.shineDark ?? m.shine};`,
    `${p}-shadow: ${m.shadow};`,
  ];
}

{
  const L = [];
  L.push("/* Generated by design/build.mjs from tokens.json. Do not edit. */", ":root {");
  L.push(`  --font-ui: ${t.font.family.ui};`, `  --font-display: ${t.font.family.display};`, `  --font-mono: ${t.font.family.mono};`);
  L.push(`  --font-features: ${t.font.features};`);
  for (const [k, v] of Object.entries(t.font.size)) L.push(`  --text-${kebab(k)}: ${v}px;`);
  for (const [k, v] of Object.entries(t.radius)) L.push(`  --radius-${kebab(k)}: ${k === "appIcon" ? v * 100 + "%" : v + "px"};`);
  for (const [k, v] of Object.entries(t.spacing)) L.push(`  --space-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(t.size)) L.push(`  --size-${kebab(k)}: ${v}px;`);
  for (const [k, v] of Object.entries(t.color.accent)) L.push(`  --accent-${k}: ${v};`);
  for (const [k, v] of Object.entries(t.color.trafficLight)) L.push(`  --tl-${kebab(k)}: ${v};`);
  L.push("  --accent: var(--accent-blue);");
  for (const [k, v] of Object.entries(t.color.light)) L.push(`  --${kebab(k)}: ${v};`);
  for (const [k, v] of Object.entries(t.material)) if (!k.startsWith("_")) material(k, v).forEach((l) => L.push("  " + l));
  for (const [k, s] of Object.entries(springs)) {
    L.push(`  --spring-${k}: ${cssLinear(s)};`);
    L.push(`  --spring-${k}-duration: ${s.duration}ms;`);
  }
  for (const [k, v] of Object.entries(t.motion.duration)) L.push(`  --dur-${k}: ${v}ms;`);
  L.push("}", "", ':root[data-theme="dark"] {');
  for (const [k, v] of Object.entries(t.color.dark)) L.push(`  --${kebab(k)}: ${v};`);
  for (const [k, v] of Object.entries(t.material)) if (!k.startsWith("_")) L.push(`  --mat-${kebab(k)}-tint: ${v.tintDark};`);
  L.push("}", "");
  writeFileSync(join(out, "tokens.css"), L.join("\n"));
  // The prototype is served standalone, so it gets its own copy.
  mkdirSync(join(here, "..", "prototype", "assets"), { recursive: true });
  writeFileSync(join(here, "..", "prototype", "assets", "tokens.css"), L.join("\n"));
}

// ---------------------------------------------------------------- QML
{
  const q = [];
  q.push("// Generated by design/build.mjs from tokens.json. Do not edit.", "pragma Singleton", "import QtQuick", "", "QtObject {");
  q.push("    property bool dark: false", "");
  q.push(`    readonly property string fontUi: "SF Pro Text"`, `    readonly property string fontDisplay: "SF Pro Display"`);
  for (const [k, v] of Object.entries(t.font.size)) q.push(`    readonly property real text${k[0].toUpperCase() + k.slice(1)}: ${v}`);
  for (const [k, v] of Object.entries(t.radius)) if (k !== "appIcon") q.push(`    readonly property real radius${k[0].toUpperCase() + k.slice(1)}: ${Math.min(v, 9999)}`);
  for (const [k, v] of Object.entries(t.size)) q.push(`    readonly property real size${k[0].toUpperCase() + k.slice(1)}: ${v}`);
  for (const [k, v] of Object.entries(t.color.accent)) q.push(`    readonly property color accent${k[0].toUpperCase() + k.slice(1)}: "${v}"`);
  // The system accent (gsettings org.gnome.desktop.interface accent-color, set in
  // Settings › Appearance); the shell and the apps keep accentName in step with it.
  q.push(`    property string accentName: "blue"`);
  // Settings › Appearance › Liquid Glass and Accessibility (desktop.json).
  q.push(`    property string glassStyle: "clear"`, `    property bool reduceTransparency: false`, `    property bool reduceMotion: false`);
  q.push(`    readonly property color accent: ({ blue: accentBlue, teal: accentBlue, purple: accentPurple, pink: accentPink, red: accentRed, orange: accentOrange, yellow: accentYellow, green: accentGreen, slate: accentGraphite })[accentName] ?? accentBlue`);
  for (const k of Object.keys(t.color.light)) {
    q.push(`    readonly property color ${k}: dark ? "${qmlColor(t.color.dark[k])}" : "${qmlColor(t.color.light[k])}"`);
  }
  for (const [k, m] of Object.entries(t.material)) {
    if (k.startsWith("_")) continue;
    q.push(`    readonly property QtObject ${k}: QtObject {`,
      `        readonly property real blur: ${m.blur}`,
      `        readonly property color tint: dark ? "${qmlColor(m.tintDark)}" : "${qmlColor(m.tintLight)}"`,
      `        readonly property color rim: dark ? "${qmlColor(m.rimDark ?? m.rim)}" : "${qmlColor(m.rim)}"`,
      `        readonly property color rimLow: dark ? "${qmlColor(m.rimLowDark ?? m.rimLow)}" : "${qmlColor(m.rimLow)}"`,
      `        readonly property color shine: dark ? "${qmlColor(m.shineDark ?? m.shine)}" : "${qmlColor(m.shine)}"`,
      `        readonly property color edge: "${qmlColor(m.edge)}"`,
      `        readonly property real lens: ${m.lens}`,
      `        readonly property real shadowY: ${m.shadowY}`,
      `        readonly property real shadowOpacity: ${m.shadowOpacity}`,
      `        readonly property real tinted: ${m.tinted}`,
      `        readonly property real reduced: ${m.reduced}`,
      "    }");
  }
  q.push("", "    // Springs: use as NumberAnimation { duration: Theme.snappy.duration; easing.type: Easing.BezierSpline; easing.bezierCurve: Theme.snappy.curve }");
  for (const [k, s] of Object.entries(springs)) {
    q.push(`    readonly property QtObject ${k}: QtObject {`,
      `        readonly property int duration: ${s.duration}`,
      `        readonly property var curve: [${qtBezierSpline(s).join(", ")}]`,
      "    }");
  }
  q.push("}", "");
  writeFileSync(join(out, "Theme.qml"), q.join("\n"));
  writeFileSync(join(out, "qmldir"), "singleton Theme 1.0 Theme.qml\n");
  // One theme module for everything: apps/lib/theme. The shell reaches it through
  // shell/ui (a link to apps/lib), so shell and shared controls share one singleton.
  for (const dir of [join(here, "..", "apps", "lib", "theme")]) {
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "Theme.qml"), q.join("\n"));
    // Release.qml (the system's name and version) lives beside the theme.
    writeFileSync(join(dir, "qmldir"), "singleton Theme 1.0 Theme.qml\nsingleton Release 1.0 Release.qml\n");
  }
}

// QML wants #AARRGGBB.
function qmlColor(c) {
  const m = c.match(/rgba?\(([^)]+)\)/);
  if (!m) return c;
  const [r, g, b, a = 1] = m[1].split(",").map((x) => parseFloat(x));
  const hex = (n) => Math.round(n).toString(16).padStart(2, "0");
  return `#${hex(a * 255)}${hex(r)}${hex(g)}${hex(b)}`;
}

// ---------------------------------------------------------------- GTK / libadwaita
{
  // Colours as CSS variables (libadwaita's own plus --gg-* for design/gtk/theme.css),
  // one block per appearance; the rules themselves live in theme.css.
  const vars = (scheme) => {
    const c = t.color[scheme], g = t.color.gtk[scheme], sys = t.color.system[scheme];
    const v = {};
    // libadwaita builds the system accent from these, so the user's accent choice
    // comes out in Apple's tones.
    for (const [k, col] of Object.entries(sys)) v[`accent-${k}`] = col;
    Object.assign(v, {
      "accent-fg-color": "#ffffff",
      "destructive-bg-color": sys.red, "destructive-fg-color": "#ffffff", "destructive-color": sys.red,
      "success-bg-color": sys.green, "success-fg-color": "#ffffff", "success-color": sys.green,
      "warning-bg-color": sys.orange, "warning-fg-color": "#ffffff", "warning-color": sys.orange,
      "error-bg-color": sys.red, "error-fg-color": "#ffffff", "error-color": sys.red,
      "window-bg-color": c.windowBg, "window-fg-color": c.label,
      "view-bg-color": c.contentBg, "view-fg-color": c.label,
      "headerbar-bg-color": c.windowBg, "headerbar-fg-color": c.label, "headerbar-backdrop-color": c.windowBg,
      "headerbar-border-color": "transparent", "headerbar-shade-color": "transparent", "headerbar-darker-shade-color": "transparent",
      "sidebar-bg-color": g.sidebar, "sidebar-fg-color": c.label, "sidebar-backdrop-color": g.sidebar,
      "sidebar-border-color": "transparent", "sidebar-shade-color": "transparent",
      "secondary-sidebar-bg-color": c.contentBg, "secondary-sidebar-fg-color": c.label,
      "secondary-sidebar-backdrop-color": c.contentBg, "secondary-sidebar-border-color": c.separator,
      "card-bg-color": c.fill, "card-fg-color": c.label, "card-shade-color": c.separator,
      "dialog-bg-color": c.windowBg, "dialog-fg-color": c.label,
      "popover-bg-color": g.menu, "popover-fg-color": c.label, "popover-shade-color": c.separator,
      "thumbnail-bg-color": c.contentBg, "thumbnail-fg-color": c.label,
      "shade-color": c.separator,
      "border-color": c.separator,
      "dim-opacity": "62%",
      "window-radius": `${t.radius.window}px`,
      "gg-label": c.label, "gg-secondary-label": c.secondaryLabel, "gg-tertiary-label": c.tertiaryLabel,
      "gg-separator": c.separator, "gg-fill": c.fill, "gg-selection": c.selection,
      "gg-red": sys.red, "gg-orange": sys.orange,
      "gg-tl-close": t.color.trafficLight.close, "gg-tl-minimize": t.color.trafficLight.minimize,
      "gg-tl-zoom": t.color.trafficLight.zoom, "gg-tl-inactive": g.trafficInactive,
      "gg-focus-ring": "color-mix(in srgb, var(--accent-bg-color) 45%, transparent)",
      "gg-scroll-edge": `color-mix(in srgb, ${c.contentBg} 94%, transparent)`,
    });
    for (const [k, col] of Object.entries(g)) if (k !== "trafficInactive") v[`gg-${kebab(k)}`] = col;
    return v;
  };
  const block = (sel, obj) => `${sel} {\n${Object.entries(obj).map(([k, v]) => `  --${k}: ${v};`).join("\n")}\n}`;
  const css = [
    "/* Generated by design/build.mjs from tokens.json and design/gtk/{theme,apps}.css.",
    "   Install to ~/.config/gtk-4.0/gtk.css (GTK 4.16+, libadwaita 1.6+). */",
    block(":root", vars("light")),
    `@media (prefers-color-scheme: dark) {\n${block(":root", vars("dark")).replace(/^/gm, "  ")}\n}`,
    "",
    `* { font-family: "SF Pro Text", "Inter Variable", "Inter", sans-serif; font-feature-settings: ${t.font.features.replace(/"/g, "'")}; }`,
    "",
    readFileSync(join(here, "gtk", "theme.css"), "utf8"),
    readFileSync(join(here, "gtk", "apps.css"), "utf8"),
  ].join("\n");
  writeFileSync(join(out, "gtk.css"), css);
  writeFileSync(join(out, "gtk3.css"), "/* Generated by design/build.mjs from design/gtk/gtk3.css. Install to ~/.config/gtk-3.0/gtk.css. */\n" +
    readFileSync(join(here, "gtk", "gtk3.css"), "utf8"));
}

// ---------------------------------------------------------------- Hyprland
{
  const lines = ["# Generated by design/build.mjs from tokens.json. Do not edit.", "animations {", "    enabled = true"];
  for (const [k, s] of Object.entries(springs)) lines.push(`    bezier = ${k}, ${hyprBezier(s.dampingFraction).join(", ")}`);
  const ds = (k) => Math.max(1, Math.round(springs[k].duration / 100));
  lines.push(
    // The shell's launch card (shell/AppLaunch.qml) carries the motion of an app
    // opening; the window itself only settles in underneath it.
    `    animation = windowsIn, 1, ${ds("smooth")}, smooth, popin 96%`,
    `    animation = windowsOut, 1, ${ds("snappy")}, smooth, popin 92%`,
    `    animation = windowsMove, 1, ${ds("snappy")}, snappy`,
    `    animation = layersIn, 1, ${ds("popover")}, popover, popin 90%`,
    `    animation = layersOut, 1, 2, smooth, fade`,
    `    animation = fade, 1, 2, smooth`,
    `    animation = workspaces, 1, ${ds("smooth")}, smooth, slide`,
    // The yellow light parks windows on special:minimized; they sink and fade.
    `    animation = specialWorkspace, 1, ${ds("window")}, window, slidefadevert 30%`,
    "}",
    "",
    "decoration {",
    `    rounding = ${t.radius.window}`,
    "    blur {",
    "        enabled = true",
    `        size = ${Math.round(t.material.glassRegular.blur / 3)}`,
    "        passes = 3",
    `        vibrancy = ${round(t.material.glassRegular.saturate - 1, 2)}`,
    "        noise = 0.012",
    "        popups = true",
    "    }",
    "    shadow {",
    "        enabled = true",
    "        range = 40",
    "        render_power = 3",
    "        color = rgba(0000002e)",
    "        offset = 0 12",
    "    }",
    "}",
    ""
  );
  writeFileSync(join(out, "hyprland-motion.conf"), lines.join("\n"));
}

console.log("tokens built:", Object.entries(springs).map(([k, s]) => `${k}=${s.duration}ms`).join(" "));
