[Icon Theme]
Name=Golden Gate
Comment=Original icon theme for the Golden Gate desktop
Inherits=Adwaita,hicolor
Directories=scalable/apps,scalable/places,scalable/mimetypes,scalable/devices,symbolic/actions,512x512/apps,512x512/places,512x512/mimetypes,512x512/devices

[scalable/apps]
Size=128
MinSize=16
MaxSize=512
Type=Scalable
Context=Applications

[scalable/places]
Size=128
MinSize=16
MaxSize=512
Type=Scalable
Context=Places

[scalable/mimetypes]
Size=128
MinSize=16
MaxSize=512
Type=Scalable
Context=MimeTypes

[scalable/devices]
Size=128
MinSize=16
MaxSize=512
Type=Scalable
Context=Devices

[symbolic/actions]
Size=16
MinSize=8
MaxSize=512
Type=Scalable
Context=Actions

[512x512/apps]
Size=512
Type=Threshold
Context=Apps

[512x512/places]
Size=512
Type=Threshold
Context=Places

[512x512/mimetypes]
Size=512
Type=Threshold
Context=Mimetypes

[512x512/devices]
Size=512
Type=Threshold
Context=Devices
