#!/usr/bin/env python3
"""Archive and distribute a project (Product ▸ Archive, then the Organizer):

    lcode_archive.py stage ROOT                  lay out the release build as an installable app
    lcode_archive.py install ROOT [PREFIX]       install it (default ~/.local): Applications finds it
    lcode_archive.py uninstall ID [PREFIX]
    lcode_archive.py pkgbuild ROOT               dist/arch: a PKGBUILD and its sources (makepkg -si)
    lcode_archive.py flatpak ROOT                dist/flatpak: a flatpak-builder manifest
    lcode_archive.py tarball ROOT                dist/<name>-<version>.tar.gz with an install.sh

The staged app (.build/archive/<slug>) is a prefix tree:
    bin/<slug>                                   the program, or a launcher for it
    share/<slug>/…                               its files (Python sources, a Golden Gate app)
    share/applications/<id>.desktop
    share/icons/hicolor/scalable/apps/<id>.svg
    share/metainfo/<id>.metainfo.xml
"""
from __future__ import annotations

import datetime
import html
import json
import os
import pathlib
import shutil
import stat
import subprocess
import sys
import tarfile

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import lcode_icon as icons  # noqa: E402
import lcode_project as proj  # noqa: E402

FLATPAK_RUNTIME = ("org.gnome.Platform", "org.gnome.Sdk", "49")
CATEGORIES = {"Utility", "Development", "Education", "Game", "Graphics", "AudioVideo", "Network", "Office", "Science", "Settings", "System"}
PERMISSIONS = {
    "network": ["--share=network"],
    "home": ["--filesystem=home"],
    "documents": ["--filesystem=xdg-documents"],
    "downloads": ["--filesystem=xdg-download"],
    "pictures": ["--filesystem=xdg-pictures"],
    "music": ["--filesystem=xdg-music"],
    "videos": ["--filesystem=xdg-videos"],
    "notifications": ["--talk-name=org.freedesktop.Notifications"],
    "sound": ["--socket=pulseaudio"],
    "graphics": ["--device=dri"],
    "devices": ["--device=all"],
    "location": ["--system-talk-name=org.freedesktop.GeoClue2"],
    "host": ["--talk-name=org.freedesktop.Flatpak"],
}


class Info:
    """What an archive needs to know about a project."""

    def __init__(self, root: str) -> None:
        p = proj.open_project(root)
        self.root = pathlib.Path(p["root"])
        self.p = p
        self.meta = p["meta"]
        self.toolchain = p["toolchain"]
        self.kind = p["kind"]
        self.name = p["displayName"] or p["name"]
        self.slug = proj.slug_name(self.name)
        bundle = p["bundleId"] or proj.bundle_identifier("org.example", self.name)
        # The id the running app reports (and so its desktop file's name): GTK
        # needs a valid D-Bus name; Quickshell apps use their AppId pragma as is.
        self.app_id = bundle if self.toolchain == "goldengate" else proj.application_id(bundle)
        self.version = str(self.meta.get("version") or "1.0")
        self.build = str(self.meta.get("build") or "1")
        self.product = (p["products"] or [self.slug])[0]
        self.stage = self.root / ".build" / "archive" / self.slug
        self.dist = self.root / "dist"


# ----------------------------------------------------------------- stage

def launcher(target: str) -> str:
    """A shell launcher that finds the app relative to itself (any prefix)."""
    return ('#!/bin/sh\n# Generated by LCode.\nhere=$(dirname "$(readlink -f "$0")")\n'
            f"exec {target} \"$@\"\n")


def write_exec(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def copy_tree(src: pathlib.Path, dst: pathlib.Path, skip=("__pycache__", ".git", ".lcode", ".build", "dist", "tests", "build",
                                                            "build-release", "target", ".venv", "venv")) -> None:
    shutil.copytree(src, dst, symlinks=False, ignore=shutil.ignore_patterns(*skip, "*.pyc", ".*"), dirs_exist_ok=True)


def desktop_entry(info: Info, exec_path: str) -> str:
    m = info.meta
    category = m.get("category") if m.get("category") in CATEGORIES else ("Development" if info.kind == "tool" else "Utility")
    lines = ["[Desktop Entry]", "Type=Application", f"Name={info.name}", f"Exec={exec_path}", f"Icon={info.app_id}",
             f"Categories={category};", f"Terminal={'true' if info.kind == 'tool' else 'false'}",
             f"StartupWMClass={info.app_id}", "X-LCode-Project=true"]
    if m.get("comment"):
        lines.insert(3, f"Comment={m['comment']}")
    if m.get("keywords"):
        lines.append("Keywords=" + ";".join(k.strip() for k in str(m["keywords"]).split(",") if k.strip()) + ";")
    return "\n".join(lines) + "\n"


def metainfo(info: Info) -> str:
    m = info.meta
    today = datetime.date.today().isoformat()
    summary = html.escape(m.get("comment") or f"{info.name}, made with LCode")
    dev = html.escape(m.get("organization") or proj.author_name())
    homepage = f'\n  <url type="homepage">{html.escape(m["homepage"])}</url>' if m.get("homepage") else ""
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>{info.app_id}</id>
  <name>{html.escape(info.name)}</name>
  <summary>{summary}</summary>
  <metadata_license>CC0-1.0</metadata_license>
  <project_license>{html.escape(m.get("license") or "MIT")}</project_license>
  <developer id="{html.escape(info.app_id.rsplit('.', 1)[0])}"><name>{dev}</name></developer>
  <launchable type="desktop-id">{info.app_id}.desktop</launchable>{homepage}
  <releases><release version="{html.escape(info.version)}" date="{today}"/></releases>
  <content_rating type="oars-1.1"/>
</component>
"""


def stage(root: str, out=print) -> Info:
    """Lay the release build out as an installable tree."""
    info = Info(root)
    if info.kind == "library":
        raise RuntimeError("A library isn't an app to archive. Use it from an app or a tool.")
    if info.stage.exists():
        shutil.rmtree(info.stage)
    bin_dir = info.stage / "bin"
    share = info.stage / "share" / info.slug
    bin_dir.mkdir(parents=True)
    t = info.toolchain
    if t in ("swift", "cargo", "meson"):
        built = {"swift": info.root / ".build" / "release" / info.product,
                 "cargo": info.root / "target" / "release" / info.product,
                 "meson": info.root / "build-release" / info.product}[t]
        if not built.is_file():
            raise RuntimeError(f"The release build wasn't found at {built}. Archive builds it first; check the log.")
        share.mkdir(parents=True)
        shutil.copy2(built, share / info.product)
        # SwiftPM keeps a target's resources in bundles beside the program.
        for bundle in built.parent.glob("*.resources"):
            shutil.copytree(bundle, share / bundle.name, dirs_exist_ok=True)
        write_exec(bin_dir / info.slug, launcher(f'"$here/../share/{info.slug}/{info.product}"'))
    elif t == "python":
        copy_tree(info.root, share)
        main = proj.toolchains.python_main(info.root) or "main.py"
        write_exec(bin_dir / info.slug, launcher(f'python3 "$here/../share/{info.slug}/{main}"'))
    elif t == "goldengate":
        app = info.root / ".build" / "app"
        if not (app / "App.qml").is_file():
            raise RuntimeError("Build the app first: the archive is made from .build/app.")
        shutil.copytree(app, share, symlinks=False, dirs_exist_ok=True,
                        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "tests"))
        write_exec(bin_dir / info.slug, launcher(f'qs -n -p "$here/../share/{info.slug}/App.qml"'))
    else:
        raise RuntimeError("LCode doesn't know how to archive this project.")

    icon_dir = info.stage / "share" / "icons" / "hicolor" / "scalable" / "apps"
    icon_dir.mkdir(parents=True)
    icon = info.meta.get("icon") or icons.default_icon(t, info.meta.get("accent") or "#0a84ff", info.kind)
    (icon_dir / f"{info.app_id}.svg").write_text(icons.render(icon, False, info.root), encoding="utf-8")
    apps = info.stage / "share" / "applications"
    apps.mkdir(parents=True)
    (apps / f"{info.app_id}.desktop").write_text(desktop_entry(info, info.slug), encoding="utf-8")
    meta_dir = info.stage / "share" / "metainfo"
    meta_dir.mkdir(parents=True)
    (meta_dir / f"{info.app_id}.metainfo.xml").write_text(metainfo(info), encoding="utf-8")
    (info.stage / "lcode-archive.json").write_text(json.dumps({
        "name": info.name, "id": info.app_id, "slug": info.slug, "version": info.version, "build": info.build,
        "toolchain": t, "kind": info.kind, "date": datetime.datetime.now().isoformat(timespec="seconds"),
    }, indent=2) + "\n", encoding="utf-8")
    size = sum(f.stat().st_size for f in info.stage.rglob("*") if f.is_file())
    out(f"Archived {info.name} {info.version} ({info.build}): {size // 1024} KB in {info.stage}")
    return info


def archive_summary(root: str) -> dict:
    info = Info(root)
    data = {}
    try:
        data = json.loads((info.stage / "lcode-archive.json").read_text())
    except (OSError, ValueError):
        pass
    size = sum(f.stat().st_size for f in info.stage.rglob("*") if f.is_file()) if info.stage.exists() else 0
    record = installed_record(info.app_id)
    return {"archived": bool(data), "archive": data, "size": size, "appId": info.app_id, "name": info.name, "version": info.version,
            "installed": bool(record), "installedAt": record.get("prefix", "") if record else "",
            "flatpak": info.toolchain != "goldengate", "toolchain": info.toolchain}


# --------------------------------------------------------------- install

def data_home() -> pathlib.Path:
    return pathlib.Path(os.environ.get("XDG_DATA_HOME") or pathlib.Path.home() / ".local" / "share")


def default_prefix() -> pathlib.Path:
    """~/.local, or wherever XDG_DATA_HOME's share folder lives."""
    data = data_home()
    return data.parent if data.name == "share" else pathlib.Path.home() / ".local"


def record_path(app_id: str) -> pathlib.Path:
    return data_home() / "lcode" / "installed" / f"{app_id}.json"


def installed_record(app_id: str) -> dict:
    try:
        return json.loads(record_path(app_id).read_text())
    except (OSError, ValueError):
        return {}


def install(root: str, prefix: str | None = None, out=print) -> dict:
    info = Info(root)
    if not (info.stage / "lcode-archive.json").is_file():
        raise RuntimeError("Archive the project first (Product ▸ Archive).")
    base = pathlib.Path(prefix) if prefix else default_prefix()
    files = []
    for src in sorted(info.stage.rglob("*")):
        rel = src.relative_to(info.stage)
        if rel.name == "lcode-archive.json" or src.is_dir():
            continue
        dst = base / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        files.append(str(dst))
    # The desktop entry runs the program by its full path: ~/.local/bin isn't always on PATH.
    entry = base / "share" / "applications" / f"{info.app_id}.desktop"
    entry.write_text(desktop_entry(info, str(base / "bin" / info.slug)), encoding="utf-8")
    for tool in (["update-desktop-database", str(entry.parent)], ["gtk-update-icon-cache", "-qtf", str(base / "share/icons/hicolor")]):
        if shutil.which(tool[0]):
            subprocess.run(tool, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    record = {"id": info.app_id, "name": info.name, "version": info.version, "prefix": str(base), "files": files}
    record_path(info.app_id).parent.mkdir(parents=True, exist_ok=True)
    record_path(info.app_id).write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    out(f"Installed {info.name} in {base}. It's in Applications.")
    return {"path": str(entry), "message": f"{info.name} is installed. Find it in Applications."}


def uninstall(app_id: str, out=print) -> dict:
    record = installed_record(app_id)
    if not record:
        raise RuntimeError(f"{app_id} isn't installed by LCode.")
    folders = set()
    for f in record.get("files", []):
        path = pathlib.Path(f)
        if path.is_file() or path.is_symlink():
            path.unlink()
            folders.add(path.parent)
    # Remove the app's own folders once they're empty.
    for folder in sorted(folders, key=lambda p: len(p.parts), reverse=True):
        for parent in [folder, *folder.parents]:
            if parent == pathlib.Path(record["prefix"]) or not parent.is_dir() or any(parent.iterdir()):
                break
            parent.rmdir()
    record_path(app_id).unlink()
    out(f"Removed {record.get('name', app_id)}.")
    return {"message": f"{record.get('name', app_id)} was removed."}


# ---------------------------------------------------------------- export

ARCH_DEPENDS = {
    ("goldengate", "app"): ["quickshell", "qt6-svg"],
    ("python", "app"): ["python", "python-gobject", "gtk4", "libadwaita"],
    ("python", "tool"): ["python"],
    ("cargo", "app"): ["gtk4", "libadwaita"],
    ("cargo", "tool"): ["gcc-libs"],
    ("meson", "app"): ["gtk4", "libadwaita"],
    ("meson", "tool"): ["glibc"],
    ("swift", "app"): ["gtk4"],
    ("swift", "tool"): ["glibc"],
}


def tar_stage(info: Info, path: pathlib.Path, top: str) -> pathlib.Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(path, "w:gz") as tar:
        for src in sorted(info.stage.rglob("*")):
            if src.is_file() and src.name != "lcode-archive.json":
                tar.add(src, arcname=f"{top}/{src.relative_to(info.stage)}")
    return path


def pkgbuild(root: str, out=print) -> dict:
    info = Info(root)
    if not (info.stage / "lcode-archive.json").is_file():
        raise RuntimeError("Archive the project first (Product ▸ Archive).")
    folder = info.dist / "arch"
    if folder.exists():
        shutil.rmtree(folder)
    top = f"{info.slug}-{info.version}"
    tarball = tar_stage(info, folder / f"{top}.tar.gz", top)
    import hashlib
    digest = hashlib.sha256(tarball.read_bytes()).hexdigest()
    depends = " ".join(f"'{d}'" for d in ARCH_DEPENDS.get((info.toolchain, info.kind), []))
    m = info.meta
    lic = (m.get("license") or "MIT").replace("'", "")
    desc = (m.get("comment") or f"{info.name}, made with LCode").replace("'", "’")
    url = m.get("homepage") or ""
    pkgver = "".join(c if c.isalnum() or c in "._" else "_" for c in info.version)
    text = f"""# Maintainer: {m.get("organization") or proj.author_name()}
# Generated by LCode. Build and install with: makepkg -si
pkgname={info.slug}
pkgver={pkgver}
pkgrel={info.build if info.build.isdigit() else 1}
pkgdesc='{desc}'
arch=('x86_64')
url='{url}'
license=('{lic}')
depends=({depends})
options=('!strip' '!debug')
source=('{top}.tar.gz')
sha256sums=('{digest}')

package() {{
  cd "$srcdir/{top}"
  install -d "$pkgdir/usr"
  cp -a bin share "$pkgdir/usr/"
}}
"""
    (folder / "PKGBUILD").write_text(text, encoding="utf-8")
    out(f"Wrote {folder / 'PKGBUILD'}. To build and install the package: cd {folder} && makepkg -si")
    return {"path": str(folder), "message": "A PKGBUILD is ready. In a terminal, run makepkg -si in its folder to build and install the package."}


def flatpak(root: str, out=print) -> dict:
    info = Info(root)
    if info.toolchain == "goldengate":
        raise RuntimeError("Golden Gate apps run on Quickshell, which isn't available as a Flatpak runtime. "
                           "Install the app on this computer, or export a PKGBUILD for Golden Gate and Arch.")
    caps = info.meta.get("capabilities")
    if caps is None:
        caps = ["network"] if info.kind == "app" else []
    finish = ["--share=ipc", "--socket=fallback-x11", "--socket=wayland"] + [a for c in caps for a in PERMISSIONS.get(c, [])]
    runtime, sdk, version = FLATPAK_RUNTIME
    t = info.toolchain
    if t == "meson":
        module = {"name": info.slug, "buildsystem": "meson", "sources": [{"type": "dir", "path": "../.."}]}
        command = info.product
        extensions = []
    elif t == "python":
        main = proj.toolchains.python_main(info.root) or "main.py"
        module = {"name": info.slug, "buildsystem": "simple",
                  "build-commands": [f"mkdir -p /app/share/{info.slug} /app/bin",
                                     f"cp -a . /app/share/{info.slug}/",
                                     f"printf '#!/bin/sh\\nexec python3 /app/share/{info.slug}/{main} \"$@\"\\n' > /app/bin/{info.slug}",
                                     f"chmod +x /app/bin/{info.slug}"],
                  "sources": [{"type": "dir", "path": "../.."}]}
        command = info.slug
        extensions = []
    elif t == "cargo":
        module = {"name": info.slug, "buildsystem": "simple",
                  "build-options": {"append-path": "/usr/lib/sdk/rust-stable/bin", "env": {"CARGO_HOME": "/run/build/" + info.slug + "/cargo"}},
                  "build-commands": ["cargo --offline fetch --manifest-path Cargo.toml || cargo fetch",
                                     "cargo build --release",
                                     f"install -Dm755 target/release/{info.product} /app/bin/{info.product}"],
                  "sources": [{"type": "dir", "path": "../.."}]}
        command = info.product
        extensions = ["org.freedesktop.Sdk.Extension.rust-stable"]
    else:
        module = {"name": info.slug, "buildsystem": "simple",
                  "build-options": {"append-path": "/usr/lib/sdk/swift/bin"},
                  "build-commands": ["swift build -c release --static-swift-stdlib",
                                     f"install -Dm755 .build/release/{info.product} /app/bin/{info.product}"],
                  "sources": [{"type": "dir", "path": "../.."}]}
        command = info.product
        extensions = ["org.freedesktop.Sdk.Extension.swift6"]
    assets = {"name": "desktop-files", "buildsystem": "simple",
              "build-commands": [f"install -Dm644 {info.app_id}.desktop /app/share/applications/{info.app_id}.desktop",
                                 f"install -Dm644 {info.app_id}.svg /app/share/icons/hicolor/scalable/apps/{info.app_id}.svg",
                                 f"install -Dm644 {info.app_id}.metainfo.xml /app/share/metainfo/{info.app_id}.metainfo.xml"],
              "sources": [{"type": "file", "path": f"{info.app_id}.desktop"}, {"type": "file", "path": f"{info.app_id}.svg"},
                          {"type": "file", "path": f"{info.app_id}.metainfo.xml"}]}
    manifest = {"id": info.app_id, "runtime": runtime, "runtime-version": version, "sdk": sdk, "command": command,
                "finish-args": finish, "modules": [module, assets]}
    if extensions:
        manifest["sdk-extensions"] = extensions
    folder = info.dist / "flatpak"
    folder.mkdir(parents=True, exist_ok=True)
    (folder / f"{info.app_id}.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (folder / f"{info.app_id}.desktop").write_text(desktop_entry(info, command), encoding="utf-8")
    icon = info.meta.get("icon") or icons.default_icon(t, info.meta.get("accent") or "#0a84ff", info.kind)
    (folder / f"{info.app_id}.svg").write_text(icons.render(icon, False, info.root), encoding="utf-8")
    (folder / f"{info.app_id}.metainfo.xml").write_text(metainfo(info), encoding="utf-8")
    hint = f"flatpak-builder --user --install --force-clean build {info.app_id}.json"
    out(f"Wrote {folder / (info.app_id + '.json')}. Build and install it with: cd {folder} && {hint}")
    return {"path": str(folder), "message": f"A Flatpak manifest is ready. In its folder, run: {hint}"}


def tarball(root: str, out=print) -> dict:
    info = Info(root)
    if not (info.stage / "lcode-archive.json").is_file():
        raise RuntimeError("Archive the project first (Product ▸ Archive).")
    top = f"{info.slug}-{info.version}"
    staging = info.root / ".build" / "tarball"
    if staging.exists():
        shutil.rmtree(staging)
    shutil.copytree(info.stage, staging / top, ignore=shutil.ignore_patterns("lcode-archive.json"))
    write_exec(staging / top / "install.sh", f"""#!/bin/sh
# Install {info.name} for you (into ~/.local), or for everyone with: sudo ./install.sh /usr/local
set -eu
here=$(dirname "$(readlink -f "$0")")
prefix=${{1:-$HOME/.local}}
mkdir -p "$prefix"
cp -a "$here/bin" "$here/share" "$prefix/"
sed -i "s|^Exec=.*|Exec=$prefix/bin/{info.slug}|" "$prefix/share/applications/{info.app_id}.desktop"
command -v update-desktop-database >/dev/null && update-desktop-database "$prefix/share/applications" || true
echo "{info.name} is installed in $prefix."
""")
    path = info.dist / f"{top}.tar.gz"
    path.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(path, "w:gz") as tar:
        tar.add(staging / top, arcname=top)
    shutil.rmtree(staging)
    out(f"Wrote {path}")
    return {"path": str(path), "message": "A portable archive is ready. Unpack it anywhere and run install.sh."}


def main(argv: list[str]) -> int:
    try:
        if len(argv) >= 3 and argv[1] == "stage":
            stage(argv[2], out=lambda s: print(s, flush=True))
            return 0
        if len(argv) >= 3 and argv[1] == "install":
            install(argv[2], argv[3] if len(argv) > 3 else None)
            return 0
        if len(argv) >= 3 and argv[1] == "uninstall":
            uninstall(argv[2])
            return 0
        if len(argv) >= 3 and argv[1] in ("pkgbuild", "flatpak", "tarball"):
            {"pkgbuild": pkgbuild, "flatpak": flatpak, "tarball": tarball}[argv[1]](argv[2])
            return 0
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"error: {exc}", flush=True)
        return 1
    print(__doc__, file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
