#!/bin/sh
# Write the part of the Hyprland config that depends on the machine:
# ~/.config/hypr/golden-gate/machine.conf, sourced last by hyprland.conf.
# gg-session runs this before every start of the desktop; scripts/install.sh runs
# it once. Run it again after moving an install to other hardware.
out="${1:-${XDG_CONFIG_HOME:-$HOME/.config}/hypr/golden-gate/machine.conf}"
mkdir -p "$(dirname "$out")"

virt=$(systemd-detect-virt --vm 2>/dev/null) || virt=none
software=no
if [ "${LIBGL_ALWAYS_SOFTWARE:-0}" = 1 ] || ! ls /dev/dri/renderD* >/dev/null 2>&1; then
  software=yes
fi

{
  echo "# Generated by machine-conf.sh (virtual machine: $virt, software rendering: $software)."
  echo "# It is rewritten at every session start; put your own settings in hyprland.conf."

  if [ "$virt" != none ]; then
    cat <<'EOF'

# Virtual screens report no physical size, which Hyprland's automatic scale reads
# as an extremely dense display, so it doubles everything. Use 1×.
monitor = , preferred, auto, 1
EOF
  fi

  if [ "$software" = yes ]; then
    cat <<'EOF'

# No GPU: every frame is drawn by the CPU (Mesa llvmpipe). Keep the glass, drop
# what costs the most: a lighter blur, no window shadows, shorter and smaller zooms.
decoration:blur:passes = 1
decoration:blur:size = 8
decoration:shadow:enabled = false
animation = windowsIn, 1, 3, smooth, popin 96%
animation = windowsOut, 1, 2, smooth, fade
animation = layersIn, 1, 3, smooth, fade
animation = workspaces, 1, 4, smooth, slide
# Qt's own 2D renderer draws the shell with a fraction of the CPU that OpenGL on
# llvmpipe needs, and looks the same (only the menu bar's faint shadow is lost).
env = QT_QUICK_BACKEND,software
EOF
  fi
} > "$out.tmp" && mv "$out.tmp" "$out"
