// Builds the Setup Assistant's shaders for Qt Quick (ShaderEffect needs .qsb).
//
//   node apps/setup/shaders/build.mjs      (needs qsb: qt6-shadertools, or QSB=/path/to/qsb)
//
// liquid-glass.frag is generated from the compositor's shader
// (compositor/liquid-glass/liquid-glass.frag), so there is one Liquid Glass:
// only the header changes (Qt's uniform block and texture coordinates), and the
// item may cover just the glass shape, so its rect is added as itemRect.
// glass-stroke.frag (the glass "hello") is written for Qt directly.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..", "..");
const src = readFileSync(join(root, "compositor", "liquid-glass", "liquid-glass.frag"), "utf8");

const header = `#version 440
// GENERATED by apps/setup/shaders/build.mjs from compositor/liquid-glass/liquid-glass.frag.
layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;
layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;
    vec2 screenSize;
    vec4 surfaceRect;
    float radius;
    float bezel;
    float strength;
    vec2 lightDir;
    vec4 tint;
    vec4 itemRect;      // the ShaderEffect's own rect in screen pixels
};
layout(binding = 1) uniform sampler2D tex;
`;
let body = src
  .replace(/^precision .*$/m, "")
  .replace(/^varying .*$/m, "")
  .replace(/^uniform .*$/gm, "")
  .replace(/texture2D\(/g, "texture(")
  .replace("void main() {", "void main() {\n    vec2 v_texcoord = (itemRect.xy + qt_TexCoord0 * itemRect.zw) / screenSize;")
  .replace(/gl_FragColor = (.*);/, "fragColor = ($1) * qt_Opacity;");
if (!body.includes("fragColor =")) throw new Error("liquid-glass.frag: output line not found");
writeFileSync(join(here, "liquid-glass.frag"), header + body);

const qsb = process.env.QSB || ["/usr/lib/qt6/bin/qsb", "/usr/bin/qsb"].find(existsSync) || "qsb";
for (const f of ["liquid-glass.frag", "glass-stroke.frag"]) {
  execFileSync(qsb, ["--glsl", "100 es,120,150", "--hlsl", "50", "--msl", "12", "-o", join(here, f + ".qsb"), join(here, f)], { stdio: "inherit" });
  console.log("built", f + ".qsb");
}
