#version 440
// GENERATED by apps/setup/shaders/build.mjs from compositor/liquid-glass/liquid-glass.frag.
layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;
layout(std140, binding = 0) uniform buf {
    mat4 qt_Matrix;
    float qt_Opacity;
    vec2 screenSize;
    vec4 surfaceRect;
    float radius;
    float bezel;
    float strength;
    vec2 lightDir;
    vec4 tint;
    vec4 itemRect;      // the ShaderEffect's own rect in screen pixels
};
layout(binding = 1) uniform sampler2D tex;
// Liquid Glass — ultra pass
//
// Runs over the compositor's already-blurred backdrop inside each glass shape
// (see README.md). GLSL ES 1.00; test/render.mjs compiles and renders it in CI.
// Uniforms (supplied per glass shape):
//
//   tex         blurred backdrop in screen space
//   screenSize  screen size in pixels
//   surfaceRect x, y, w, h of the glass surface in pixels
//   radius      rounded corner radius in pixels
//   bezel       optical edge/thickness width in pixels
//   strength    maximum refraction amount in pixels
//   lightDir    normalized 2D light direction
//   tint        premultiplied tint color
//
// The effect is deliberately built from several restrained optical layers:
//   1. analytic rounded-rect mask
//   2. shallow lens / volume refraction
//   3. multi-tap "thickness" sampling
//   4. very small chromatic dispersion
//   5. Fresnel-like grazing response
//   6. directional specular ribbon
//   7. interior soft reflection + edge transmission
//
// No extra uniforms are required.














const float PI = 3.14159265359;

float sat(float x) {
    return clamp(x, 0.0, 1.0);
}

vec2 safeNormalize(vec2 v) {
    return v / max(length(v), 1e-5);
}

// Signed distance to a rounded rectangle.
float sdRoundRect(vec2 p, vec2 halfSize, float r) {
    r = min(r, min(halfSize.x, halfSize.y));
    vec2 q = abs(p) - halfSize + r;
    return length(max(q, 0.0)) + min(max(q.x, q.y), 0.0) - r;
}

float sampleLuma(vec3 c) {
    return dot(c, vec3(0.2126, 0.7152, 0.0722));
}

vec3 sampleSafe(vec2 uv) {
    return texture(
        tex,
        clamp(uv, vec2(0.001), vec2(0.999))
    ).rgb;
}

void main() {
    vec2 v_texcoord = (itemRect.xy + qt_TexCoord0 * itemRect.zw) / screenSize;
    vec2 frag = v_texcoord * screenSize;

    vec2 halfSize = surfaceRect.zw * 0.5;
    vec2 centre = surfaceRect.xy + halfSize;
    vec2 p = frag - centre;

    float d = sdRoundRect(p, halfSize, radius);

    // Analytic coverage. d is in pixels with a unit gradient, so fwidth(d) is
    // about 1 (up to 1.41 on diagonals); a constant avoids needing
    // GL_OES_standard_derivatives, which GLSL ES 1.00 requires for fwidth().
    float aa = 1.25;
    float coverage = 1.0 - smoothstep(-aa, aa, d);

    if (coverage <= 0.001) {
        discard;
    }

    // ---------------------------------------------------------------------
    // 1) Stable SDF normal
    // ---------------------------------------------------------------------
    float eps = max(0.8, min(screenSize.x, screenSize.y) * 0.00055);

    float dx1 = sdRoundRect(p + vec2(eps, 0.0), halfSize, radius);
    float dx2 = sdRoundRect(p - vec2(eps, 0.0), halfSize, radius);
    float dy1 = sdRoundRect(p + vec2(0.0, eps), halfSize, radius);
    float dy2 = sdRoundRect(p - vec2(0.0, eps), halfSize, radius);

    vec2 n = safeNormalize(vec2(dx1 - dx2, dy1 - dy2));
    vec2 t = vec2(-n.y, n.x);

    // ---------------------------------------------------------------------
    // 2) Optical zones
    //
    // d < 0 : inside the glass
    // edge   : near perimeter
    // depth  : fades from edge toward center
    // ---------------------------------------------------------------------
    float edgeWidth = max(bezel, 1.0);

    float edge = 1.0 - sat((-d) / edgeWidth);
    edge = smoothstep(0.0, 1.0, edge);

    // Extra-thin outer shell used for highlight and dispersion.
    float shell = 1.0 - sat((-d) / max(edgeWidth * 0.42, 1.0));
    shell = shell * shell * (3.0 - 2.0 * shell);

    // A broad optical body that subtly changes the backdrop even in the
    // middle of a large panel.
    float bodyFade = 1.0 - sat((-d) / max(edgeWidth * 2.8, 1.0));
    bodyFade = smoothstep(0.0, 1.0, bodyFade);

    // A center weighting keeps large panels from becoming completely flat.
    vec2 q = p / max(halfSize, vec2(1.0));
    float centreFalloff = 1.0 - sat(length(q) * 0.58);
    centreFalloff = smoothstep(0.0, 1.0, centreFalloff);

    // ---------------------------------------------------------------------
    // 3) Curvature estimate
    //
    // Rounded corners have stronger optical power than long straight edges.
    // This estimate is intentionally soft to avoid visible "corner blobs".
    // ---------------------------------------------------------------------
    vec2 cornerExtent = max(abs(p) - (halfSize - vec2(radius)), vec2(0.0));
    float cornerDistance = length(cornerExtent);
    float cornerness = sat(
        1.0 - cornerDistance / max(radius * 0.95, 1.0)
    );
    cornerness = smoothstep(0.0, 1.0, cornerness);

    // Corner glass has slightly stronger lens power.
    float lensPower = mix(0.72, 1.18, cornerness);

    // ---------------------------------------------------------------------
    // 4) Directional light basis
    // ---------------------------------------------------------------------
    vec2 l = safeNormalize(lightDir);
    vec2 lightT = vec2(-l.y, l.x);

    float facing = sat(dot(n, -l));
    float oppositeFacing = sat(dot(n, l));
    float grazing = pow(1.0 - facing, 2.35);

    // ---------------------------------------------------------------------
    // 5) Layered lens displacement
    //
    // Rather than one strong edge offset, use a broad shallow lens plus a
    // small near-edge bend. This gives the "liquid" part of Liquid Glass.
    // ---------------------------------------------------------------------
    float maxStrength = max(strength, 0.0);

    vec2 broadLens =
        n * maxStrength *
        mix(0.035, 0.085, bodyFade) *
        (0.55 + 0.45 * centreFalloff);

    vec2 edgeLens =
        -n * maxStrength *
        shell *
        mix(0.62, 1.00, cornerness);

    vec2 directionalBend =
        t * maxStrength *
        shell *
        (0.06 + 0.045 * grazing);

    vec2 totalPx = broadLens + edgeLens + directionalBend;

    // Keep the interior nearly stable. The strongest movement occurs in
    // the optical shell, not across the whole card.
    totalPx *= mix(0.56, 1.0, edge);

    vec2 uv = (frag + totalPx) / screenSize;

    // ---------------------------------------------------------------------
    // 6) Multi-tap backdrop integration
    //
    // Four small taps make the refraction feel volumetric instead of like a
    // single texture lookup with an offset.
    // ---------------------------------------------------------------------
    vec2 px = vec2(1.0) / screenSize;

    vec2 tapN = n * px * (0.65 + 1.0 * shell);
    vec2 tapT = t * px * 0.42;

    vec3 c0 = sampleSafe(uv);
    vec3 c1 = sampleSafe(uv + tapN);
    vec3 c2 = sampleSafe(uv - tapN);
    vec3 c3 = sampleSafe(uv + tapT);
    vec3 c4 = sampleSafe(uv - tapT);

    vec3 integrated =
        c0 * 0.52 +
        c1 * 0.16 +
        c2 * 0.16 +
        c3 * 0.08 +
        c4 * 0.08;

    // ---------------------------------------------------------------------
    // 7) Subtle chromatic dispersion
    //
    // Very small separation, mostly confined to the outer optical shell.
    // ---------------------------------------------------------------------
    float dispersionPx = min(maxStrength * 0.055, 1.15) * shell;
    vec2 dispersion = n * dispersionPx / screenSize;

    vec3 rc = sampleSafe(uv + dispersion);
    vec3 gc = integrated;
    vec3 bc = sampleSafe(uv - dispersion);

    vec3 spectral = vec3(
        mix(integrated.r, rc.r, 0.42),
        gc.g,
        mix(integrated.b, bc.b, 0.42)
    );

    // Blend dispersion into the integrated image only where it matters.
    vec3 base = mix(integrated, spectral, shell * 0.75);

    // ---------------------------------------------------------------------
    // 8) Edge transmission
    //
    // A very soft internal transmission band produces depth without a
    // painted-on white line.
    // ---------------------------------------------------------------------
    float transmission =
        shell *
        (0.018 + 0.040 * grazing) *
        (0.78 + 0.22 * centreFalloff);

    // The transmission is directionally weighted by the light.
    transmission *= (0.72 + 0.28 * facing);

    // ---------------------------------------------------------------------
    // 9) Broad reflection / Fresnel
    // ---------------------------------------------------------------------
    float fresnel =
        shell *
        (0.05 + 0.18 * grazing + 0.035 * oppositeFacing);

    // Broad, low-frequency highlight.
    float broadHighlight =
        fresnel *
        (0.55 + 0.45 * sat(dot(n, -l)));

    // Long directional ribbon. This creates the characteristic fluid-glass
    // highlight rather than a uniform perimeter glow.
    float ribbonAxis = sat(dot(t, lightT) * 0.5 + 0.5);
    float ribbon =
        pow(ribbonAxis, 7.0) *
        pow(sat(dot(n, -l)), 1.25) *
        shell *
        0.16;

    // Opposite soft catch adds dimensionality at the far edge.
    float farCatch =
        pow(oppositeFacing, 4.5) *
        shell *
        0.055;

    // A broad grazing bloom prevents the highlight from looking geometric.
    float grazingBloom =
        pow(grazing, 1.65) *
        shell *
        0.095;

    // ---------------------------------------------------------------------
    // 10) Very subtle surface micro-variation
    //
    // Static and low contrast on purpose. It breaks up mathematically
    // perfect highlights while remaining invisible as "noise".
    // ---------------------------------------------------------------------
    vec2 s = frag / max(screenSize, vec2(1.0));

    float waveA = sin(
        dot(s, vec2(173.0, 91.0)) +
        dot(s, vec2(-37.0, 149.0))
    );

    float waveB = sin(
        dot(s, vec2(-211.0, 57.0)) +
        dot(s, vec2(83.0, -127.0))
    );

    float micro = 0.5 + 0.5 * (waveA * 0.55 + waveB * 0.45);
    micro = smoothstep(0.12, 0.88, micro);

    float microResponse =
        shell *
        (micro - 0.5) *
        (0.012 + 0.020 * grazing);

    // ---------------------------------------------------------------------
    // 11) Color construction
    // ---------------------------------------------------------------------
    vec3 specular = vec3(
        broadHighlight +
        ribbon +
        farCatch +
        grazingBloom
    );

    // Tiny directional chroma in the reflected edge. Kept neutral enough to
    // read as polished glass on both light and dark backgrounds.
    vec3 edgeChroma = vec3(
        1.00 + 0.035 * grazing,
        1.00,
        1.00 + 0.050 * farCatch
    );

    specular *= edgeChroma;

    vec3 col = base;
    col += specular;
    col += vec3(transmission);
    col += vec3(microResponse);

    // Very mild interior lift. Less opacity toward the edge preserves the
    // contrast of the backdrop underneath.
    float bodyLift =
        0.012 +
        0.018 * bodyFade +
        0.008 * centreFalloff;

    col += vec3(bodyLift);

    // ---------------------------------------------------------------------
    // 12) Tint
    // ---------------------------------------------------------------------
    float tintAlpha = sat(tint.a);
    vec3 tintRgb = tint.rgb / max(tintAlpha, 1e-4);

    // A stronger tint in the interior and a weaker tint at the reflective
    // shell produces more believable depth.
    float tintMix =
        tintAlpha *
        mix(0.76, 0.92, centreFalloff) *
        mix(1.0, 0.76, shell);

    col = mix(col, tintRgb, tintMix);

    // Preserve local backdrop contrast. The optical shell gets the effect;
    // the center stays visually close to the source.
    float preserve =
        0.13 * (1.0 - shell) +
        0.04 * bodyFade;

    col = mix(col, base, preserve);

    // Slightly shape highlights based on local source luminance so bright
    // content does not produce a flat gray glass slab.
    float lum = sampleLuma(base);
    float highlightGate = mix(0.92, 1.06, 1.0 - sat(lum));
    col *= 0.995 + 0.005 * highlightGate;

    // Prevent tiny numerical excursions from producing clipped RGB.
    col = max(col, vec3(0.0));

    // ---------------------------------------------------------------------
    // 13) Output
    // ---------------------------------------------------------------------
    fragColor = (vec4(col * coverage, coverage)) * qt_Opacity;
}
